### PR TITLE
Support to (optionally) specify a branch instead of commit or tag

### LINKED ISSUE #32: Specify branch
I'm feeling the need to be riding the develop branch during the initial development phase of a project. Have you considered this as an option, and if so what are your thoughts? I did have a look at modifying, but I'm hesitant since there are a few refactors needed and I can't run tests 
https://github.com/DispatchMe/mgp/issues/31.

### PR DESCRIPTION
**Pull request by sokki**
fixes #32

### CODE REVIEW

**Comment by sokki** [comment]
Travis don't like your private package testing :disappointed: 
`Error: Git clone failed: https://github.com/DispatchMe/mgp-private-package-test.git`

**Comment by rhyslbw** [comment]
@sokki Awesome! Thanks so much!

**Comment by DominikGuzei** [comment]
Oh yeah, this would be amazing for our project! :+1:

**Comment by jperl** [comment]
Sorry, getting to this today.

**Comment by rhyslbw** [comment]
Anything we can do to help get this released @jperl? Thanks in advance

**Comment by sokki** [comment]
@rhyslbw @DominikGuzei  It would be awesome if you could test my branch against your packages combination. To install the branch on your system:
```
git clone https://github.com/sokki/mgp
cd mgp
git checkout feature/specify-branch
npm link
```

**Comment by rhyslbw** [comment]
@sokki All good here :+1:

**Comment by jperl** [comment]
Tracking in #35. Thanks!

**Comment by jperl** [comment]
This has been merged and released. Thanks @sokki

**Comment by rhyslbw** [comment]
Thanks @jperl

**Pull request closed without merging**
