### PR TITLE
Generalises Packages.toHttps to not require GitHub urls

### PR DESCRIPTION
**Pull request by rhyslbw**
Includes tests

### CODE REVIEW

**Comment by rhyslbw** [comment]
Hmm. I had to comment out the actual private repo clone test during dev since the [creds are loaded from ENVs in Travis](https://github.com/DispatchMe/mgp/blob/master/.travis.yml#L5). Without this the suite was passing…

**Comment by jperl** [comment]
Taking a look -- thanks

**Comment by jperl** [comment]
@rhyslbw I tried to clone that repo locally but was unable --- so I would guess the build is failing since CI does not have access either.

**Comment by rhyslbw** [comment]
I've only defined those fake packages in the toHttps unit test, so it shouldn't be called elsewhere

**Comment by jperl** [comment]
Gotcha

**Comment by jperl** [comment]
The tests passed for me locally as well, so I pushed your branch to the main repo and the build passed. It seems that travis will not export private build variables to PRs for security purposes.

**Comment by rhyslbw** [comment]
Ah I see, thanks for the prompt attention :+1:

**Pull request merged**
